pipeline{
    agent any
    stages {
          stage('Hello') {
            steps {
                git branch: 'main', url: 'https://github.com/Natali149/teste-e2e-ebac.git'
                bat 'npm install'
            }
        }
           stage('Teste') {
            steps {
             bat '''set NO_COLOR=1
             npm test'''
            }
        }
    }
}